<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AlumnoAsignaturaSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('alumno_asignatura')->insert([
            // Alumnos 1-10: Principalmente en DAW
            ['idAlumno' => 1, 'idAsignatura' => 1],
            ['idAlumno' => 1, 'idAsignatura' => 2],
            ['idAlumno' => 1, 'idAsignatura' => 3],
            ['idAlumno' => 1, 'idAsignatura' => 5],
            ['idAlumno' => 2, 'idAsignatura' => 1],
            ['idAlumno' => 2, 'idAsignatura' => 4],
            ['idAlumno' => 2, 'idAsignatura' => 5],
            ['idAlumno' => 3, 'idAsignatura' => 2],
            ['idAlumno' => 3, 'idAsignatura' => 3],
            ['idAlumno' => 3, 'idAsignatura' => 5],
            ['idAlumno' => 4, 'idAsignatura' => 1],
            ['idAlumno' => 4, 'idAsignatura' => 2],
            ['idAlumno' => 4, 'idAsignatura' => 4],
            ['idAlumno' => 4, 'idAsignatura' => 5],
            ['idAlumno' => 5, 'idAsignatura' => 1],
            ['idAlumno' => 5, 'idAsignatura' => 2],
            ['idAlumno' => 5, 'idAsignatura' => 3],
            ['idAlumno' => 6, 'idAsignatura' => 2],
            ['idAlumno' => 6, 'idAsignatura' => 3],
            ['idAlumno' => 6, 'idAsignatura' => 4],
            ['idAlumno' => 6, 'idAsignatura' => 5],
            ['idAlumno' => 7, 'idAsignatura' => 1],
            ['idAlumno' => 7, 'idAsignatura' => 3],
            ['idAlumno' => 7, 'idAsignatura' => 5],
            ['idAlumno' => 8, 'idAsignatura' => 1],
            ['idAlumno' => 8, 'idAsignatura' => 2],
            ['idAlumno' => 8, 'idAsignatura' => 4],
            ['idAlumno' => 9, 'idAsignatura' => 2],
            ['idAlumno' => 9, 'idAsignatura' => 3],
            ['idAlumno' => 9, 'idAsignatura' => 4],
            ['idAlumno' => 9, 'idAsignatura' => 5],
            ['idAlumno' => 10, 'idAsignatura' => 1],
            ['idAlumno' => 10, 'idAsignatura' => 2],
            ['idAlumno' => 10, 'idAsignatura' => 5],

            // Alumnos 11-25: Principalmente en DAM
            ['idAlumno' => 11, 'idAsignatura' => 6],
            ['idAlumno' => 11, 'idAsignatura' => 7],
            ['idAlumno' => 11, 'idAsignatura' => 8],
            ['idAlumno' => 12, 'idAsignatura' => 6],
            ['idAlumno' => 12, 'idAsignatura' => 7],
            ['idAlumno' => 12, 'idAsignatura' => 9],
            ['idAlumno' => 13, 'idAsignatura' => 6],
            ['idAlumno' => 13, 'idAsignatura' => 8],
            ['idAlumno' => 13, 'idAsignatura' => 9],
            ['idAlumno' => 14, 'idAsignatura' => 7],
            ['idAlumno' => 14, 'idAsignatura' => 8],
            ['idAlumno' => 14, 'idAsignatura' => 9],
            ['idAlumno' => 15, 'idAsignatura' => 6],
            ['idAlumno' => 15, 'idAsignatura' => 7],
            ['idAlumno' => 15, 'idAsignatura' => 8],
            ['idAlumno' => 15, 'idAsignatura' => 9],
            ['idAlumno' => 16, 'idAsignatura' => 6],
            ['idAlumno' => 16, 'idAsignatura' => 7],
            ['idAlumno' => 17, 'idAsignatura' => 7],
            ['idAlumno' => 17, 'idAsignatura' => 8],
            ['idAlumno' => 17, 'idAsignatura' => 9],
            ['idAlumno' => 18, 'idAsignatura' => 6],
            ['idAlumno' => 18, 'idAsignatura' => 8],
            ['idAlumno' => 18, 'idAsignatura' => 9],
            ['idAlumno' => 19, 'idAsignatura' => 6],
            ['idAlumno' => 19, 'idAsignatura' => 7],
            ['idAlumno' => 19, 'idAsignatura' => 9],
            ['idAlumno' => 20, 'idAsignatura' => 7],
            ['idAlumno' => 20, 'idAsignatura' => 8],
            ['idAlumno' => 21, 'idAsignatura' => 6],
            ['idAlumno' => 21, 'idAsignatura' => 7],
            ['idAlumno' => 21, 'idAsignatura' => 8],
            ['idAlumno' => 22, 'idAsignatura' => 6],
            ['idAlumno' => 22, 'idAsignatura' => 9],
            ['idAlumno' => 23, 'idAsignatura' => 7],
            ['idAlumno' => 23, 'idAsignatura' => 8],
            ['idAlumno' => 23, 'idAsignatura' => 9],
            ['idAlumno' => 24, 'idAsignatura' => 6],
            ['idAlumno' => 24, 'idAsignatura' => 7],
            ['idAlumno' => 24, 'idAsignatura' => 8],
            ['idAlumno' => 24, 'idAsignatura' => 9],
            ['idAlumno' => 25, 'idAsignatura' => 6],
            ['idAlumno' => 25, 'idAsignatura' => 8],

            // Alumnos 26-40: Principalmente en ASIR
            ['idAlumno' => 26, 'idAsignatura' => 10],
            ['idAlumno' => 26, 'idAsignatura' => 11],
            ['idAlumno' => 26, 'idAsignatura' => 12],
            ['idAlumno' => 27, 'idAsignatura' => 10],
            ['idAlumno' => 27, 'idAsignatura' => 11],
            ['idAlumno' => 27, 'idAsignatura' => 13],
            ['idAlumno' => 28, 'idAsignatura' => 11],
            ['idAlumno' => 28, 'idAsignatura' => 12],
            ['idAlumno' => 28, 'idAsignatura' => 13],
            ['idAlumno' => 29, 'idAsignatura' => 10],
            ['idAlumno' => 29, 'idAsignatura' => 12],
            ['idAlumno' => 29, 'idAsignatura' => 13],
            ['idAlumno' => 30, 'idAsignatura' => 10],
            ['idAlumno' => 30, 'idAsignatura' => 11],
            ['idAlumno' => 30, 'idAsignatura' => 12],
            ['idAlumno' => 30, 'idAsignatura' => 13],
            ['idAlumno' => 31, 'idAsignatura' => 10],
            ['idAlumno' => 31, 'idAsignatura' => 11],
            ['idAlumno' => 32, 'idAsignatura' => 11],
            ['idAlumno' => 32, 'idAsignatura' => 12],
            ['idAlumno' => 32, 'idAsignatura' => 13],
            ['idAlumno' => 33, 'idAsignatura' => 10],
            ['idAlumno' => 33, 'idAsignatura' => 12],
            ['idAlumno' => 33, 'idAsignatura' => 13],
            ['idAlumno' => 34, 'idAsignatura' => 10],
            ['idAlumno' => 34, 'idAsignatura' => 11],
            ['idAlumno' => 34, 'idAsignatura' => 13],
            ['idAlumno' => 35, 'idAsignatura' => 11],
            ['idAlumno' => 35, 'idAsignatura' => 12],
            ['idAlumno' => 36, 'idAsignatura' => 10],
            ['idAlumno' => 36, 'idAsignatura' => 11],
            ['idAlumno' => 36, 'idAsignatura' => 12],
            ['idAlumno' => 37, 'idAsignatura' => 10],
            ['idAlumno' => 37, 'idAsignatura' => 13],
            ['idAlumno' => 38, 'idAsignatura' => 11],
            ['idAlumno' => 38, 'idAsignatura' => 12],
            ['idAlumno' => 38, 'idAsignatura' => 13],
            ['idAlumno' => 39, 'idAsignatura' => 10],
            ['idAlumno' => 39, 'idAsignatura' => 11],
            ['idAlumno' => 39, 'idAsignatura' => 12],
            ['idAlumno' => 39, 'idAsignatura' => 13],
            ['idAlumno' => 40, 'idAsignatura' => 10],
            ['idAlumno' => 40, 'idAsignatura' => 12],

            // Alumnos 41-50: Mezcla de estudios
            ['idAlumno' => 41, 'idAsignatura' => 1],
            ['idAlumno' => 41, 'idAsignatura' => 2],
            ['idAlumno' => 41, 'idAsignatura' => 6],
            ['idAlumno' => 41, 'idAsignatura' => 7],
            ['idAlumno' => 42, 'idAsignatura' => 3],
            ['idAlumno' => 42, 'idAsignatura' => 4],
            ['idAlumno' => 42, 'idAsignatura' => 5],
            ['idAlumno' => 43, 'idAsignatura' => 6],
            ['idAlumno' => 43, 'idAsignatura' => 7],
            ['idAlumno' => 43, 'idAsignatura' => 10],
            ['idAlumno' => 43, 'idAsignatura' => 11],
            ['idAlumno' => 44, 'idAsignatura' => 10],
            ['idAlumno' => 44, 'idAsignatura' => 11],
            ['idAlumno' => 44, 'idAsignatura' => 12],
            ['idAlumno' => 45, 'idAsignatura' => 1],
            ['idAlumno' => 45, 'idAsignatura' => 2],
            ['idAlumno' => 45, 'idAsignatura' => 3],
            ['idAlumno' => 45, 'idAsignatura' => 4],
            ['idAlumno' => 45, 'idAsignatura' => 5],
            ['idAlumno' => 46, 'idAsignatura' => 8],
            ['idAlumno' => 46, 'idAsignatura' => 9],
            ['idAlumno' => 47, 'idAsignatura' => 11],
            ['idAlumno' => 47, 'idAsignatura' => 12],
            ['idAlumno' => 47, 'idAsignatura' => 13],
            ['idAlumno' => 48, 'idAsignatura' => 2],
            ['idAlumno' => 48, 'idAsignatura' => 3],
            ['idAlumno' => 48, 'idAsignatura' => 6],
            ['idAlumno' => 48, 'idAsignatura' => 7],
            ['idAlumno' => 49, 'idAsignatura' => 10],
            ['idAlumno' => 49, 'idAsignatura' => 11],
            ['idAlumno' => 50, 'idAsignatura' => 1],
            ['idAlumno' => 50, 'idAsignatura' => 4],
            ['idAlumno' => 50, 'idAsignatura' => 5],
        ]);
    }
}
